name: build-linux
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Tauri deps
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: NPM install
        run: npm ci

      - name: Build (no sign)
        run: npm run tauri build -- --ci

      - name: Unit tests
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/src-tauri/libs/linux/x86_64
        run: cargo test -p vend-os --no-default-features
